### ISSUE TITLE
Misspelling in the module-info.java

### ISSUE THREAD

**Issue by Indivikar** [dlsc-software-consulting-gmbh/PDFViewFX#3]
Hallo

I found a typo [here](https://github.com/dlsc-software-consulting-gmbh/PDFViewFX/blob/master/pdfviewfx/src/main/java/module-info.java).

`requires org.kordamp.iconli.core;`

I think it has to look like this.

`requires org.kordamp.ikonli.core;`

**Comment by dlemmermann** [comment]
In previous versions of Ikonli they had a typo. Now they fixed it. Maybe you can provide a pull request that updates the ikonli libs and fixes "our" typo?

**Comment by Indivikar** [comment]
ohh sorry, I just noticed it and was about to write it, you had already answered. I use the Ikonli version 12.1.0 and 11.5.0

**Comment by dlemmermann** [comment]
I updated the ikonli version used in PDFViewFX to 12.2.0.
