### ISSUE TITLE
PDFView not Scrollable?

### ISSUE THREAD

**Issue by todayifeeltired** [dlsc-software-consulting-gmbh/PDFViewFX#7]
Hi there, gotta disturb again.

my quick & dirty fxml:
`<AnchorPane xmlns="http://javafx.com/javafx/11" xmlns:fx="http://javafx.com/fxml/1"
            fx:controller="myController">
    <children>
        <BorderPane AnchorPane.bottomAnchor="0.0" AnchorPane.leftAnchor="0.0" AnchorPane.rightAnchor="0.0"
                    AnchorPane.topAnchor="0.0">
            <center>
                <PDFView fx:id="pdfview" minHeight="800" minWidth="1200" maxWidth="1200" maxHeight="800">
                    <GridPane.margin>
                        <Insets left="200" right="200" top="50"/>
                    </GridPane.margin>
                </PDFView>
            </center>
        </BorderPane>
    </children>
</AnchorPane>`

my controller:
` myController {

    @FXML
    private PDFView pdfview;

    private final String path;

    public myController (String path) {
        this.path = path;
    }

    @FXML
    void initialize() {
        pdfview.load(new File(path));
    }
}`

when i first enter the scene, the pdfview is not scrollable and not sized appropriate.
as sioon as i click the "show All / whole Page" on the toolbar **_twice_**, it gets scrollable and is sized perfectly.
i dont want my user to have that toolbar and i havent found a way to resize it/make it scrollable by code.
what am i missing here?

**Comment by dlemmermann** [comment]
I believe the method you were looking for is PDFView.setShowAll(). Closing issue, feel free to reopen if I missed your point.
