### ISSUE TITLE
pdfview.load(PDDocument document)

### ISSUE THREAD

**Issue by todayifeeltired** [dlsc-software-consulting-gmbh/PDFViewFX#8]
Hello there,
i am also working with pdfbox. 
I´d like the user to decide whether he wants to save the pdf he seens in the pdfview or not.
is there any way to add a `pdfview.load(PDDocument document)` method? 
i saw that you try to load it as an PDFBoxDocument anyway.

**Comment by todayifeeltired** [comment]
hello :)
are there any updates coming or should i just have a look at alternatives?
many thanks

**Comment by dlemmermann** [comment]
So what you wanted is a save method? Not the load(...) method in your comment above, right? Feel free to submit a PR. Closing issue for now.
